Repository ajktown/api, pull requests merged in 2024-02, with the labels that each got.

#81 Yarn Latest Feb 2024
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency

#77 Returns Action Group For Post Word Consistency
  k8s/deployment.yaml
  src/constants/action-group.const.ts
  src/controllers/action-group.controller.ts
  src/domains/action/action-group.domain.ts
  src/domains/action/action.domain.ts
  src/domains/action/index.interface.ts
  src/domains/word/word.domain.ts
  src/dto/get-word-query.dto.ts
  src/dto/post-action.dto.ts
  src/factories/get-word-query.factory.ts
  src/factories/index.root.ts
  src/handlers/time.handler.ts
  src/lambdas/get-env.lambda.ts
  src/main.module.ts
  src/modules/action-group.module.ts
  src/schemas/action.schema.ts
  src/schemas/index.collections.ts
  src/services/action-group.service.ts
Labels: enhancement

#84 Bug Fix for ATD set as null
  src/domains/action/action-group-ids.domain.ts
  src/domains/action/action-group.domain.ts
  src/domains/action/action-groups.domain.ts
  src/responses/get-action-groups.res.ts
  src/services/action-group.service.ts
Labels: bugfix

#83 Kubernetes like issue for this repository
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/dependency.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/infrastructure.yaml
  .github/ISSUE_TEMPLATE/performance.yaml
  .github/ISSUE_TEMPLATE/refactor.yaml
Labels: documentation

#80 Include Pronunciation and Meaning for Search
  src/factories/get-word-query.factory.ts
Labels: enhancement

#86 Bigbang change: POST/GET Action Groups
  src/constants/time-zone.const.ts
  src/controllers/action-group.controller.ts
  src/controllers/ritual.controller.ts
  src/domains/action/action-group-ids.domain.ts
  src/domains/action/action-group.domain.ts
  src/domains/action/index.interface.ts
  src/domains/ritual/index.interface.ts
  src/domains/ritual/ritual-group.domain.ts
  src/domains/ritual/ritual.domain.ts
  src/dto/index.validator.ts
  src/dto/post-action-group.dto.ts
  src/errors/400/index.num-not-in-range.error.ts
  src/handlers/time.handler.ts
  src/main.module.ts
  src/modules/ritual.module.ts
  src/responses/get-action-groups.res.ts
  src/responses/get-ritual.res.ts
  src/schemas/action-group.schema.ts
  src/services/action-group.service.ts
  src/services/ritual.service.ts
Labels: enhancement
