Repository ajktown/api, pull requests merged in 2024-03, with the labels that each got.

#87 Action group returns in time order
  src/domains/ritual/ritual-group.domain.ts
  src/domains/ritual/ritual.domain.ts
Labels: enhancement

#88 GET /users/mlajkim/rituals
  .vscode/settings.json
  src/constants/auth-mdl-excluded-paths.const.ts
  src/controllers/user.controller.ts
  src/domains/ritual/ritual-group.domain.ts
  src/domains/ritual/ritual.domain.ts
  src/domains/user/user.domain.ts
  src/errors/400/more-than-one-user-with-same-email-address.error.ts
  src/main.module.ts
  src/modules/user.module.ts
  src/services/ritual.service.ts
  src/services/user.service.ts
Labels: enhancement

#91 Managed NotFoundError (http 404 error)
  src/domains/action/action-group.domain.ts
  src/domains/action/action.domain.ts
  src/domains/shared-resource/shared-resource.domain.ts
  src/domains/user/user.domain.ts
  src/errors/404/index.error.ts
  src/errors/404/not-exist-or-no-permission.error.ts
  src/errors/404/parent-not-exist-or-no-permission.error.ts
  src/services/shared-resource.service.ts
Labels: refactor

#90 Mlajkim's action group/action is now in public
  src/constants/auth-mdl-excluded-paths.const.ts
  src/controllers/user.controller.ts
  src/domains/action/action-group.domain.ts
  src/domains/action/action.domain.ts
  src/domains/word/index.interface.ts
  src/domains/word/word.domain.ts
  src/modules/user.module.ts
  src/services/action-group.service.ts
  src/services/word.service.ts
Labels: enhancement

#94 Buy me coffee in README.md
  README.md
Labels: documentation

#97 GET /rituals returns real ritual
  src/controllers/ritual.controller.ts
  src/domains/action/action-group.domain.ts
  src/domains/ritual/index.interface.ts
  src/domains/ritual/ritual-group.domain.ts
  src/domains/ritual/ritual.domain.ts
  src/modules/ritual.module.ts
  src/modules/user.module.ts
  src/schemas/index.collections.ts
  src/schemas/ritual.schema.ts
  src/services/ritual.service.ts
Labels: enhancement

#98 PUT ritual/default
  src/controllers/ritual.controller.ts
  src/domains/ritual/index.interface.ts
  src/domains/ritual/parent-ritual.domain.ts
  src/domains/ritual/ritual-group.domain.ts
  src/domains/ritual/ritual.domain.ts
  src/dto/patch-ritual-group-body.dto.ts
  src/responses/get-ritual.res.ts
  src/schemas/ritual.schema.ts
  src/services/ritual.service.ts
Labels: enhancement

#101 Introduce dev_api for developers of API
  README.md
  src/domains/ritual/ritual.domain.ts
Labels: documentation

#100 Yarn Latest Mar 2024
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency

#102 Fix security issue `POST /action-groups/:id/action`
  src/domains/action/action-group.domain.ts
Labels: bugfix

#99 Implement api path `/api/v1/users`
  src/controllers/user.controller.ts
  src/responses/get-users.res.ts
  src/services/user.service.ts
Labels: enhancement

#107 Action Group Now Returns Level 1 for Late Commitment
  src/domains/action/action-group.domain.ts
  src/domains/action/action.domain.ts
Labels: enhancement
