Repository ajktown/api, pull requests merged in 2024-04, with the labels that each got.

#109 Yarn Latest Late Mar 2024
  package.json
  src/domains/action/action-group.domain.ts
  yarn-latest.record
  yarn.lock
Labels: dependency

#106 Delete today's actions of action group
  src/controllers/action-group.controller.ts
  src/domains/action/action-group.domain.ts
  src/services/action-group.service.ts
Labels: enhancement

#110 Preference new props recentTags
  src/domains/preference/index.interface.ts
  src/domains/preference/preference.domain.ts
  src/schemas/preference.schema.ts
Labels: enhancement

#111 Import preference model
  src/modules/action-group.module.ts
  src/modules/shared-resource.module.ts
  src/modules/user.module.ts
  src/modules/word.module.ts
  src/services/smart-word.service.ts
  src/services/word.service.ts
Labels: enhancement

#112 Post word updates preference `recentTags`
  src/domains/word/word.domain.ts
  src/services/word.service.ts
Labels: enhancement

#114 Update word updates preference `recentTags`
  src/domains/word/word.domain.ts
  src/services/word.service.ts
Labels: enhancement

#115 Yarn Latest Apr 2024
  package.json
  yarn-latest.record
  yarn.lock
Labels: dependency

#116 Fix bug where action group ids are not properly returned
  src/domains/ritual/index.interface.ts
  src/domains/ritual/parent-ritual.domain.ts
  src/domains/ritual/ritual-group.domain.ts
  src/domains/ritual/ritual.domain.ts
  src/responses/get-ritual.res.ts
  src/services/ritual.service.ts
Labels: bugfix

#117 Fix where the api does not handle undefined `PutWordByIdBodyDTO`'s `tags`
  src/domains/ritual/ritual.domain.ts
  src/domains/word/word.domain.ts
Labels: bugfix

#118 New API endpoint `/api/v1/users/mlajkim`
  src/constants/auth-mdl-excluded-paths.const.ts
  src/controllers/user.controller.ts
  src/domains/user/user.domain.ts
  src/responses/get-user.res.ts
Labels: enhancement

#119 Display name
  src/domains/user/user.domain.ts
  src/responses/get-user.res.ts
Labels: enhancement
